name: test-app

on:
    push:
        branches:
            - master
            - main

env:
    PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
    REGION: asia-south1
    REPO_NAME: test-gcp-deploy

jobs:
    build-and-deploy:
        name: Setup, Build, and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - id: 'auth'
              uses: 'google-github-actions/auth@v0'
              with:
                  credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

            # Setup gcloud CLI/SDK
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.6.0

            - name: Authorize Docker push
              run: gcloud auth configure-docker

            - name: Build and tag the docker image
              run: |-
                  docker build . --tag asia-south1-docker.pkg.dev/agprop-in/test-gcp-cloud/test:latest

            - name: Push the image to the Artifacts Registry
              run: |-
                  docker push asia-south1-docker.pkg.dev/agprop-in/test-gcp-cloud/test:latest

            - name: Deploy
              run: |-
                  gcloud run deploy $REPO_NAME \
                  --region $REGION \
                  --image asia-south1-docker.pkg.dev/agprop-in/test-gcp-cloud/test:latest \
                  --platform "managed" \
                  --quiet
